language: php
php:
  - 7.1
  - 7.2
  - 7.3

directories:
  - $HOME/.composer/cache

before_script:
  - composer install --prefer-dist

script:
  - cd tests/
  - php ../vendor/bin/phpunit --testdox

after_success:
- bash <(curl -s https://codecov.io/bash)
