language: php
php:
  - 7.1
  - 7.2
  - 7.3

directories:
  - $HOME/.composer/cache

before_script:
  - composer install --prefer-dist

script:
  - composer test:unit
  - >
    if [[ "${TRAVIS_PULL_REQUEST" == "false" ]]; then
      composer test:integration
    fi

after_success:
- bash <(curl -s https://codecov.io/bash)
