language: php
php:
  - 7.1
  - 7.2
  - 7.3

directories:
  - $HOME/.composer/cache/files

before_script:
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit --testdox --testsuite unit
  - >
    if [[ "${TRAVIS_PULL_REQUEST}" = "false" ]]; then
      vendor/bin/phpunit --testdox --testsuite integration
    fi

after_success:
- bash <(curl -s https://codecov.io/bash)
